name: CI

on: [push, pull_request]

jobs:
  check-zsh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Zsh and ShellCheck
      run: sudo apt-get install -y zsh shellcheck
    - name: Check Zsh scripts
      run: shellcheck **/*.zsh

  check-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon
        . /etc/profile.d/nix.sh
    - name: Build Nix environment
      run: nix-build
