# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@v3
        with:
          tools-deps-version: '1.10.1.727'

      - name: Run tests
        run: lein test

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Deploy Smart Contracts
        run: |
          npm install -g truffle
          truffle migrate --network mainnet
