name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix-channel --update

      - name: Setup Nix environment
        run: |
          echo "with import <nixpkgs> {}; stdenv.mkDerivation {
            name = \"my-env\";
            buildInputs = [ clojure truffle ganache-cli solc nodejs npm ];
          }" > default.nix

      - name: Enter Nix environment
        run: nix-shell

      - name: Install Shadow-CLJS
        run: npm install -g shadow-cljs

      - name: Install Clojure CLI
        run: curl -O https://download.clojure.org/install/linux-install-1.10.3.967.sh
        run: chmod +x linux-install-1.10.3.967.sh
        run: sudo ./linux-install-1.10.3.967.sh

      - name: Run tests
        run: lein test

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Deploy Smart Contracts
        run: |
          truffle migrate --network mainnet
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
